source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
inhibit_all_warnings!

target 'ElementKit_Example' do
  pod 'ElementKit', :path => '../'

  target 'ElementKit_Tests' do
    inherit! :search_paths

  end
end

